### PR TITLE
Adding fixes for ::std::abs(double)

### PR DESCRIPTION
**Pull request by IngwiePhoenix**
You need to also make it so, that the Makefile pulls LDFLAGS from `fltk-config --ldflags`. Otherwise you get _tons_ of linking errors.

### CODE REVIEW

**Comment by the-real-neil** [comment]
@IngwiePhoenix your work ethic is phenomenal, but Travis hates your patch and I don't know why. I'm still investigating, but I suspect `std::abs` collisions between `cmath` and `cstdlib`.

**Comment by the-real-neil** [comment]
okay, it has nothing to do with `<cmath>` or `<cstdlib>`; it's something about the overload set for `std::abs` when `<algorithm>` includes `<cmath>` or something. I'm going to try the function templates provided by c++11.

**Comment by the-real-neil** [comment]
Boom.

https://travis-ci.org/rubicks/rendera/builds/48700748

**Comment by IngwiePhoenix** [comment]
Awesome! :) So you got my fixes working after all.

**Comment by the-real-neil** [comment]
@IngwiePhoenix , to your credit, it was your mostly your stuff that went into the forty-something commits I did for the macosx port. I feel pretty good about offering what we have to @Mortis69 . I'd feel awesome if you could confirm that my `macosx` branch builds and installs correctly for you.

**Comment by IngwiePhoenix** [comment]
Works like a charm! But, the LIBS variable still has an issue. In general, you should be using the fltk-config tool to pick up all LDFLAGS needed to properly link a FLTK app. On OS X, this looks like so:

$ fltk-config --ldflags
-L/usr/local/lib -lfltk -lpthread -framework Cocoa

I am going to edit the generated Makefile to add that to test the build itself.

But, anything else works perfectly fine. No errors what so ever! Only the linking error. But my autotools-fu is not enough to help you with an automake patch… So that one is up to you. Here is what my LIBS variable looks like before and after i mod it.

Before:

```
LIBS = -lz -lpng -ljpeg -lfltk
```

After:

```
LIBS = -lz -lpng -ljpeg $(shell fltk-config dflags)
```

In addition, src/File.cxx needs a minor adjustment on OS X. Wrap the jpeglib.h and png.h includes in an extern „C“ {} block. This should look like:

#include <algorithm>
#include <cstdlib>
#include <cstring>
#include <algorithm>
#include <vector>
#include <setjmp.h>
extern "C" {
#include <png.h>
#include <jpeglib.h>
}

And then, it builds! :)

**Comment by the-real-neil** [comment]
@IngwiePhoenix , are you saying that, when you attempt to reproduce what Travis does (i.e., invoke build-o-matic.sh), it fails? Could you please attach or paste what build-o-matic.sh prints to stdout and/or stderr when it fails?

Also, there is a very good reason why I'm not executing `fltk-config`: the presence of that executable is not guaranteed. What's more, the different `EXEEXT` values make binary detection (let alone invocation) extremely difficult.

**Comment by IngwiePhoenix** [comment]
Ahh, I see. Actually, I wasn’t using build-o-matic.sh, but will try this now.  Then you will have to find a way to add -lpthread and -framework Cocoa by another way; these are required.

Going to try build-o-matic.sh now.

**Comment by IngwiePhoenix** [comment]
build-o-matic.sh is not running properly on my mac.

Ingwie@Ingwies-Macbook-Pro.local ~/W/osx-rendera $ ./build-o-matic.sh 
${PATH}    == "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
${MANPATH} == "/usr/local/opt/coreutils/libexec/gnuman:"
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
mkdir: /m4: Permission denied

I believe the parts that need a little fix are obvious. I’d suggest something like

if ["$(uname)" == "Darwin"]; then
    RDFLAGS=""
else
    RDFLAGS="-f";
fi

readlink $RDFLAGS $yourpathhere

**Comment by the-real-neil** [comment]
@IngwiePhoenix , you /do/ have `coreutils` installed, yes?

What do you see when you invoke

```
$ which readlink
```

?

**Comment by IngwiePhoenix** [comment]
BTW, I pretty much built by doing:

git clone -b macosx (url) osx-rendera
cd rendera
autoreconf -ivf .
./configure
make

Well, I did have to edit the Makefile to add the missing -lpthread and -framework Cocoa. Thats all I did.

**Comment by IngwiePhoenix** [comment]
Yes, I have coreutils….the OS X version. Apple forked many of the GNU projects and is using their versions of many things. And if it wasnt forked, then it came from the original BSD platform that Darwin - OS X foundation - originates from.=

**Comment by the-real-neil** [comment]
Okay, understood.

Here's what I would like from you:
- go back to `autoreconf -ivf . && ./configure && make`
- when it fails, email me the entirety of stdout and stderr

Here's what I'm promising:
- I will assume that there's a rendera link error, even though I can't duplicate it with Travis osx
- I will add (again) the autoconf and automake code to
  - detect `fltk-config`
  - add `fltk-config --cxxflags` to `rendera_CXXFLAGS`
  - add `fltk-config --ldflags` to `rendera_LDFLAGS`

Here's what I might do:
- within `build-o-matic.sh`, remove the dependency on GNU coreutils; i.e., `readlink -f`

**Comment by IngwiePhoenix** [comment]
Done. Grab it here: http://ingwie.me/blog/downloads http://ingwie.me/blog/downloads its in the Rendera folder. Each step is separated in its own TXT file. The order is probably obvious. :)

**Comment by the-real-neil** [comment]
@IngwiePhoenix , thanks, you're awesome---nice site btw.

I'll (try to) work on this over the weekend; apologies _ex post facto_ for ripping out the `fltk-config` stuff. Apologies in advance if I can't get it done by Monday.

**Comment by IngwiePhoenix** [comment]
Thats no problem at all - you’re very welcome! And thanks for the compliment.

There is no rush in you adding the fixes. After all, its your project and I am just trying to help you get it into one more platform. :)

**Comment by the-real-neil** [comment]
I cannot make this work. A week of tooling on the Travis CI darwin machines has been entirely fruitless. @IngwiePhoenix, if you can write a patch that Travis osx can swallow, I'd be very interested in seeing it. Until then, I'm stopping my work on the macosx branch.

**Pull request closed without merging**
